Full_Members/urls.py
from django.contrib import admin
from django.urls import path, include
from members.views import home_page
from django.conf.urls.static import static
from django.conf import settings
# from profile.views import user_login, user_logout
from django.contrib.auth import views as auth_views
# from model_report import report

# report.autodiscover()

admin.site.site_header = "Seasons's Members admin area"
admin.site.site_title  = "Seasons"

urlpatterns = [
    path('', home_page, name = 'index'),
    path('members/', include('members.urls', namespace = 'members')),
    # path('profile/', include('profile.urls', namespace='Profile') ),
    path('admin/', admin.site.urls),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'profile/index.html')  , name= 'logout'),
    path('login/', auth_views.LoginView.as_view(template_name = 'profile/login.html', redirect_field_name = 'members:MembersDetails' )  , name= 'login'),
    path('explorer/', include('explorer.urls')),
    path('nested_admin/', include('nested_admin.urls')),
    # path('admin_tools/', include('admin_tools.urls')),
    path('report_builder/', include('report_builder.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Reports/urls.py
from django.urls import path
# from Product.views import ProductDetail, ProductList
from .views import SearchProductView, AdvancedSearch

app_name = 'Search'

urlpatterns = [
    path('', SearchProductView.as_view(),name = 'Result'),
    path('advanced/', AdvancedSearch.as_view(), name = 'Advanced'),
    # path('single/<slug:slug>/', ProductDetail.as_view(),name = 'Single'),


]

members/urls.py
from django.urls import path, include
from members.views import (member_form, listData, MembersDetails, index, InstalmentiAPIView,
                           PaymentApiView, SearchMemberView, UpdateMemberProfile, ProfileAPI)
from profile.views import UpdateProfile
from django.contrib.auth.decorators import login_required
from rest_framework import routers

router = routers.DefaultRouter()
router.register('PaymentAPI', PaymentApiView, base_name='Payments')
router.register('InstallmentAPI', InstalmentiAPIView)
router.register('members', ProfileAPI, base_name='Members')

app_name = 'members'
instalment_list=InstalmentiAPIView.as_view({'get':'list'})
instalment_detail=InstalmentiAPIView.as_view({'get':'retrieve'})

payment_list=PaymentApiView.as_view({'get':'list'})
payment_detail=PaymentApiView.as_view({'get':'retrieve'})

update_profile=ProfileAPI.as_view({'put':'partial_update'})
member_list=ProfileAPI.as_view({'get':'list'})
member_detail=ProfileAPI.as_view({'get':'retrieve'})

urlpatterns = [

        path('', index, name='Index' ),
        path('add/', member_form, name = 'mainForm'),
        path('list/', login_required(listData.as_view()), name= 'listData'),
        path('search/<slug:slug>/', login_required(MembersDetails.as_view()), name= 'MembersDetails'),
        path('search/update/<int:pk>/',login_required(UpdateMemberProfile.as_view()), name='Update' ),
        path('search/', login_required(SearchMemberView.as_view()), name= 'Search'),
        path('api/', include(router.urls)),
        path('api/list/',  member_list, name='member-list'),
        path('api/<int:pk>/', member_detail, name='member-detail'),
        path('api/update/<int:pk>', update_profile, name='updateprofile'),
        path('api/instalments', instalment_list, name='instalment-list'),
        path('api/instalment/<int:pk>', instalment_detail, name='instalment-detail'),
        path('api/payments', payment_list, name='payment-list'),
        path('api/payment/<int:pk>/', payment_detail, name='payment-detail'),
]

members/forms.py
from django import forms
from members.models import (member, SubMemberBase, SingleParentSubmember,
                            Under21SubMeber, SpouseSubmember, SingleInLawSubmember)
from datetime import datetime, date


class member_form(forms.ModelForm):

    class Meta:
        model = member
        fields= '__all__'

    #
    # def clean_phone(self):
    #     if not self.cleaned_data['phone'] is None:
    #         dig = [str(x) for x in range(10)]
    #         # print (dig)
    #         for c in self.cleaned_data['phone']:
    #           # print (c)
    #           if not c in dig:
    #                 raise forms.ValidationError('Only digits Please')
    #     return self.cleaned_data['phone']

    # def clean_phone2(self):
    #     if not self.cleaned_data['phone2'] is None:
    #         dig = [str(x) for x in range(10)]
    #         # print (dig)
    #         for c in self.cleaned_data['phone2']:
    #           # print (c)
    #           if not c in dig:
    #                 raise forms.ValidationError('Only digits Please')
    #     return self.cleaned_data['phone2']
    #
    # def clean_fax(self):
    #     if not self.cleaned_data['fax'] is None:
    #         dig = [str(x) for x in range(10)]
    #         # print (dig)
    #         for c in self.cleaned_data['fax']:
    #           # print (c)
    #           if not c in dig:
    #                 raise forms.ValidationError('Only digits Please')
    #     return self.cleaned_data['fax']
    #
    #
    #

class SpouseSubmemberForm(forms.ModelForm):

    class Meta:
        model = SpouseSubmember
        fields= '__all__'

    #
    # def clean_phone(self):
    #     if not self.cleaned_data['phone'] is None:
    #         dig = [str(x) for x in range(10)]
    #         # print (dig)
    #         for c in self.cleaned_data['phone']:
    #           # print (c)
    #           if not c in dig:
    #                 raise forms.ValidationError('Only digits Please')
    #     return self.cleaned_data['phone']


class SingleParentSubmemberForm(forms.ModelForm):

    class Meta:
        model = SingleParentSubmember
        fields= '__all__'
    #
    #
    # def clean_phone(self):
    #     if not self.cleaned_data['phone'] is None:
    #         dig = [str(x) for x in range(10)]
    #         # print (dig)
    #         for c in self.cleaned_data['phone']:
    #           # print (c)
    #           if not c in dig:
    #                 raise forms.ValidationError('Only digits Please')
    #     return self.cleaned_data['phone']

class SingleInLawSubmemberForm(forms.ModelForm):

    class Meta:
        model = SingleInLawSubmember
        fields= '__all__'

    #
    # def clean_phone(self):
    #     if not self.cleaned_data['phone'] is None:
    #         dig = [str(x) for x in range(10)]
    #         # print (dig)
    #         for c in self.cleaned_data['phone']:
    #           # print (c)
    #           if not c in dig:
    #                 raise forms.ValidationError('Only digits Please')
    #     return self.cleaned_data['phone']


class Under21SubMeberForm(forms.ModelForm):

    class Meta:
        model = Under21SubMeber
        fields= '__all__'
    #
    # def clean_birthDay(self):
    #     today = date.today()
    #     age_defferance = (today - self.cleaned_data['birthDay']).days
    #     if age_defferance >= 7665:
    #         raise forms.ValidationError ('The age is over 21 years!')
    #     return self.cleaned_data['birthDay']

members/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy

from members import forms
from django.contrib.auth.decorators import login_required
from django.views.generic import (DetailView, ListView, FormView, CreateView,
                                  UpdateView, DeleteView)
from members.models import member, Payment, Instalment
from django.http import Http404
from rest_framework.mixins import (CreateModelMixin, DestroyModelMixin, ListModelMixin,
                                   RetrieveModelMixin, Response, UpdateModelMixin)
from rest_framework.viewsets import GenericViewSet, ViewSet, ModelViewSet
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.generics import ListAPIView, RetrieveAPIView, CreateAPIView
from .serializers import PaymentSerializer, InstallmentSerializer, MemberSerializer

# Create your views here.

def home_page(request):
    return render(request, 'home.html')

def index(request):
    return render(request, 'members/index.html')

@login_required
def member_form(request):
    myForm = forms.member_form()
    if request.method == 'POST':
        myForm = forms.member_form(request.POST, request.FILES)
        if myForm.is_valid():
            myForm.save()
            print ("The member's full name is: {} {}".format(myForm.cleaned_data['First_Name'] ,
                                                             myForm.cleaned_data['Last_Name'] ))
            return home_page(request)
    return render(request, 'members/form.html', context={'members': myForm})

class listData(ListView):
    context_object_name = 'all_members'
    model = member
    login_required = True

class MembersDetails(DetailView):

    model = member
    context_object_name = 'single_member'
    template_name = 'members/details.html'
    # template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        contexet =super(MembersDetails, self).get_context_data(*args, **kwargs)
        # context['member'] = member.objects.filter(slug = slug).first()
        print(contexet)
        return contexet

    def get_object(self, *args, **kwargs): # <== overriding the get_object to put our 404 message
        # request = self.request
        slug = self.kwargs.get('slug')
        print (slug)
        instance  = member.objects.filter(slug = slug).first()
        print (instance.memebership_type)
        if instance is None :
            raise Http404('No such member!')
        # print (instance.spousesubmember_set.all().first().profile_image.url)
        # print (instance.first_name)
        return instance

    login_required = True

class SearchMemberView(ListView):
    context_object_name = 'all_members'
    template_name = 'members/member_list.html'
    model = member
    kw = ''

    def get_queryset(self, *args, **kwargs):
        request = self.request
        self.kw = request.GET.get('q')
        print('q= ', self.kw)
        if self.kw is not None and self.kw != '':
            return member.objects.search(self.kw)
        else:
            return member.objects.all()


    def get_context_data(self, *args, **kwargs):
        context = super(SearchMemberView, self).get_context_data(*args, **kwargs)
        if  self.kw != '':
            context['header'] = 'Search results...'
            context['q'] = self.kw
        else:
            context['header'] = 'No results!\n Check the full list: '
            # context['q'] = self.query
        return context


class UpdateMemberProfile(UpdateView):
    model = member
    fields = ['facebook', 'twitter', 'instagarm', 'addetional_email']
    template_name = 'members/member_update_form.html'
    success_url = reverse_lazy('members:listData')

    def get_context_data(self, *args, **kwargs):
        contexet =super(UpdateMemberProfile, self).get_context_data(*args, **kwargs)
        # context['member'] = member.objects.filter(slug = slug).first()
        print(contexet)
        return contexet


# -----------------------------------------------------------------------------


class ProfileAPI(ListModelMixin, RetrieveModelMixin, UpdateModelMixin, GenericViewSet):
    """ Hi this is my first ModelViewSet """
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)
    serializer_class = MemberSerializer
    queryset = member.objects.all()

    def list(self, request):
        # queryset = member.objects.filter(active=False)
        queryset = member.objects.all()
        serializer = MemberSerializer(queryset, many=True)
        return Response(serializer.data)

    def partial_update(self, request, pk=None):
        queryset = member.objects.all()
        item = get_object_or_404(queryset, pk=pk)
        serializer = MemberSerializer(item)
        return Response(serializer.data)


    def retrieve(self, request, pk=None):
        queryset = member.objects.all()
        item = get_object_or_404(queryset, pk=pk)
        serializer = MemberSerializer(item)
        return Response(serializer.data)

    # def perform_update(self, serializer):
    #     if serializer.validated_data['twitter'] == '':
    #         instance = serializer.save(twitter = 'No Twitter account!')

class PaymentApiView(UpdateModelMixin, ListModelMixin, RetrieveModelMixin, GenericViewSet):
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)
    serializer_class = PaymentSerializer
    queryset = Payment.objects.all()

    def list(self, request):
        queryset = Payment.objects.all()
        serializer = PaymentSerializer(queryset, many=True, context={'request':request})
        return Response(serializer.data)

    def retrieve(self, request, pk=None):
        queryset = Payment.objects.all()
        item = get_object_or_404(queryset, pk=pk, context={'request':request})
        serializer = PaymentSerializer(item)
        return Response(serializer.data)



class InstalmentiAPIView(UpdateModelMixin, ListModelMixin, RetrieveModelMixin, GenericViewSet):
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)
    serializer_class = InstallmentSerializer
    queryset = Instalment.objects.all()

    def list(self, request):
        queryset = Instalment.objects.all()
        serializer = InstallmentSerializer(queryset, many=True, context={'request':request})
        return Response(serializer.data)

    def retrieve(self, request, pk=None):
        queryset = Instalment.objects.all()
        item = get_object_or_404(queryset, pk=pk)
        serializer = InstallmentSerializer(item, context={'request':request})
        return Response(serializer.data)



# class InstalmentListAPIView(ListAPIView):
#     queryset = Instalment.objects.all()
#     serializer_class = InstallmentSerializer
#     # permission_classes = [AllowAny]
#     # filter_backends = [SearchFilter, OrderingFilter]
#     # search_fields = ['title', 'slug']
#
#
# class InstalmentDetailAPIView(RetrieveAPIView):
#     queryset = Instalment.objects.all()
#     serializer_class = InstallmentSerializer
#     # permission_classes = [AllowAny]
#
#

templates/members/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static "/css/mycss4.css" %}">
    {# <link rel="stylesheet" href="{% static "/css/new.css" %}">#}
    <title></title>
  </head>
  <body>
    <nav class= "navbar navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand">Saesons Members</a>
      <a href="{% url 'members:Index' %}">Members</a>
      {# <a href="{% url 'members:mainForm' %}">Add Staff</a>#}
      {# <a href="{% url 'members:listData' %}">List Memebers</a>#}
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
      {% else %}
        <a href="{% url 'login' %}">Login</a>
      {% endif %}
      <a href="{% url 'index' %}">Home</a>
      {% if user.is_staff %}
      <a href="{% url 'admin:index'%}">Admin Page</a>
      <form class="form-inline my-6 my-lg-2" method="get" action="{% url 'members:Search' %}">
          <input class="form-control mr-sm-4" type="search" placeholder="Search" name = 'q' aria-label="Search">
          <button class="btn btn-outline-success my-5 my-sm-2" type="submit">Search</button>
      </form>
      {% endif %}
      <br>
    </nav>
    <br>
    {% block body_block %}
    <div class="">

    </div>
    {% endblock %}
  </body>
</html>

templates/members/details.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
{% block content %}
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Season Member Profile</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
  {% block body_block %}
  <style>
  body {
      font: 20px Montserrat, sans-serif;
      line-height: 1.8;
      color: #f5f6f7;
  }
  p {font-size: 16px;}
  .margin {margin-bottom: 45px;}
  .bg-1 {
    /*  background-color: #1abc9c;  Green */
    background-color: #2bc48c;
      color: #ffffff;
  }
  .bg-2 {
      background-color: #474e5d; /* Dark Blue */
      color: #ffffff;
  }
  .bg-3 {
    /*  background-color: #ffffff;  White */
    /*  color: #555555; */
      color:white;
      background-image: url(http://www.seasonscountryclub.com/images/slider/04.jpg);
      background-size:cover;
      text-shadow: 1px 1px black;
  }
  .bg-4 {
      background-color: #2f2f2f; /* Black Gray */
      color: #fff;
  }
  .container-fluid {
      padding-top: 70px;
      padding-bottom: 70px;
  }
  .navbar {
      padding-top: 8px;
      padding-bottom: 2px;
      border: 3;
      border-style: dotted;
      border-width: 2;
      border-radius: 10;
      border-color: red;
      margin-bottom: 0;
      font-size: 18px;
      letter-spacing: 2px;
      text-align: center;
  }
  .navbar-nav  li a:hover {
      color: #1abc9c !important;
  }

  .aa{
    display:inline;
    box-shadow: 0 6px 12px 0 rgba(0, 0, 0, 0.4), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    padding-bottom: 6px;
    width: 50%;
  }

  .ab{
    display:inline;
    box-shadow: 0 6px 12px 0 rgba(0, 0, 0, 0.4), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    padding-bottom: 6px;
    width: 50%;
    border-style: dotted;
    border-width: 2;
    border-radius: 10;
    border-color: cyan;
  }

  .abc{
    background-color: rgba(155, 200, 200, 0.4);
    display:block;
    width:50%;
    text-align: center;
    margin-left: auto;
    margin-right: auto;
    border-width: 2;
    border-style: solid;
    border-radius: 10;
    border-color: blue;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  }

.all{
  width:96%;
  text-align: center;
  margin-left: auto;
  margin-right: auto;
}


  </style>
<div class="all">
  <nav class= "navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand">Saesons Members</a>
    <a href="{% url 'members:Index' %}">Members</a>
    {# <a href="{% url 'members:mainForm' %}">Add Staff</a>#}
    {# <a href="{% url 'members:listData' %}">List Memebers</a>#}
    {% if user.is_authenticated %}
      <a href="{% url 'logout' %}">Logout</a>
    {% else %}
      <a href="{% url 'login' %}">Login</a>
    {% endif %}
    <a href="{% url 'index' %}">Home</a>
    {% if user.is_staff %}
    <a href="{% url 'admin:index'%}">Admin Page</a>
    <form class="form-inline my-4 my-lg-2" method="get" action="{% url 'members:Search' %}">
        <input class="form-control mr-sm-3" type="search" placeholder="Search" name = 'q' aria-label="Search">
        <button class="btn btn-outline-success my-3 my-sm-2" type="submit">Search</button>
    </form>
    {% endif %}
    <br>
  </nav>

<!-- First Container -->


<div class="container-fluid bg-1 text-center">
  <h1 class="margin" style="color:yellow;font-weight:bold;">Memeber Details Page</h1>
  {% if  single_member.profile_image.url != ""%}
   <img src="{{ single_member.profile_image.url }}" class="img-responsive img-circle margin" style="display:inline;box-shadow: 0 6px 12px 0 rgba(0, 0, 0, 0.4), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" alt="Bird" width="350" height="350" id="image1" >
  {% else %}
   <p> No image uploaded for this member</p>
  {% endif %}
  <div class="col-sm-6 ab">
    <br>
  {% if single_member.active %}
    <h2 style="color:green;">الإشتراك ساري</h2>
    {% if single_member.memebership_type == 'N' %}
      <h3>إشتراك سنوي</h3>
      <p style="color:red;"> المدة المتبقية على التجديد: {{single_member.days_left_to_renewal}} يوم </p>
      {% endif %}
      {% if single_member.memebership_type == 'F' %} <h3> إشتراك مجاني </h3> {% endif %}
      {% if single_member.memebership_type == 'L' %} <h3> إشتراك مدى الحياة </h3> {% endif %}
  {% else %}
    <h2 style="color:red;"> الإشتراك غير ساري </h2>
    {% if single_member.memebership_type == 'N' %}
      <h3>إشتراك سنوي</h3>
      <p style="color:red;">{{single_member.renewal_date}} : تاريخ إنتهاء العضوية   </p>
    {% endif %}
    {% if single_member.memebership_type == 'F' %} <h3> إشتراك مجاني </h3> {% endif %}
    {% if single_member.memebership_type == 'L' %} <h3> إشتراك مدى الحياة </h3> {% endif %}
  {% endif %}
  <p>Membership Code: {{ single_member.memebership_code }}</p>
  <p>First name: {{ single_member.first_name }} - Last name: {{ single_member.last_name }}</p>
  <hr>
  <br>
</div>

<!-- Second Container -->
  {% if single_member.spousesubmember_set.all %}
    <div class="container-fluid bg-3 text-center">
      <div class="abc">
      <h2>Spouse</h2>

      {% for sub in single_member.spousesubmember_set.all %}

        <br>
        <h3>Spouse Name: {{sub.first_name}} {{sub.last_name}}</h3>
        <br>
        {% if sub.profile_image %}
          <img id="image2" src="{{ sub.profile_image.url }}" hight= "250" width="250" alt="">
        {% endif %}

      </div>

      {% endfor %}
  {% endif %}
  <hr>
  <hr>
  <br>
  
  {% if single_member.under21submeber_set.all %}
  <div class="container-fluid bg-3 text-center">
    <h2>Children</h2>
    {% for sub in single_member.under21submeber_set.all %}
    <div class="col-sm-6 aa">
      <h3>Under21 member name: {{sub.first_name}} {{sub.last_name}}</h3>
      {% if sub.profile_image %}
        <img id="image2" src="{{ sub.profile_image.url }}" hight= "50%" width="50%" alt="">
      {% endif %}
    </div>
    {% endfor %}
  {% endif %}
  <hr>
</div>
  <br>
  {% if single_member.singleparentsubmember_set.all %}
  <h2>Parents</h2>
    {% for sub in single_member.singleparentsubmember_set.all %}
      <h3>Name: {{sub.first_name}} {{sub.last_name}}</h3>
      {% if sub.profile_image %}
      <img id="image2" src="{{ sub.profile_image.url }}" hight= "250" width="250" alt="">
    {% endif %}
    {% endfor %}
  {% endif %}
  <br>

</div>
<hr>
<hr>
<!-- Third Container (Grid) -->
  {% if single_member.User_Name == user%}
<div class="container-fluid bg-1 text-center">
  <h2 class="margin" style="color:yellow;font-weight:bold;">My Profile</h2>
  <a href="{% url 'members:Update' pk=single_member.pk %}" class="btn btn-primary">Edit profile</a>
  <div class="row">
    <br>
    <div class="col-sm-4" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
      <h3 style="color:blue;text-shadow: 1px 1px black;">Personal</h3>
      <br>
      <p>Name: {{single_member.first_name}} {{single_member.last_name}}</p>
        <p>Birthday: {{ single_member.birthDay }}</p>
        <p>Age: {{single_member.age}}</p>
      <br>
    </div>
    <div class="col-sm-4" >
      <h3 style="color:blue;text-shadow: 1px 1px black;">Work</h3>
      <br>
      <p>Job Title: {{ single_member.job_title }} </p>
      <p>Work Place: {{ single_member.company }} </p>
    </div>
    <div class="col-sm-4" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
      <h3 style="color:blue;text-shadow: 1px 1px black;">Contacts & Social</h3>
      <br>
      <p>Phone: {{single_member.phone}}</p>
      <p>Email: {{single_member.email}}</p>
      <p>{{single_member.facebook}}</p>
      <p>{{single_member.twitter}}</p>
    </div>
  </div>
</div>
{% endif %}

</div>
<!-- Footer -->
<footer class="container-fluid bg-4 text-center">
  <p> @copy </p>
</footer>
{% endblock %}
</body>
</html>
{% endblock %}

templates/members/form.html
<!DOCTYPE html>
{% extends "members/base.html" %}
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block body_block %}

    <form class="form-control mybg1" action="" method="post" enctype="multipart/form-data">
      {{ members.User_Name.errors }}
      <label class="mybg3" for="{{ members.User_name.id_for_label }}">User Name:</label>
      {{ members.User_Name }}
      {% csrf_token %}

      {{ members.First_Name.errors }}
      <label class="mybg3" for="{{ members.First_name.id_for_label }}">First Name:</label>
      {{ members.First_Name }}
      {% csrf_token %}

      <p></p>

      {{ members.Last_Name.errors }}
      <label class="mybg3" for="{{ members.Last_name.id_for_label }}">Last Name:</label>
      {{ members.Last_Name }}
      {% csrf_token %}

      {{ members.place.errors }}
      <label class="mybg3" for="{{ members.Last_name.id_for_label }}">Work Place:</label>
      {{ members.place }}
      {% csrf_token %}


      {{ members.Gender.errors }}
      <label class="mybg4" for="{{ members.Gender.id_for_label }}">Gender:</label>
      {{ members.Gender }}
      {% csrf_token %}

      <p></p>

      {{ members.birthDay.errors }}
      <label class="mybg4" for="{{ members.birthDay.id_for_label }}">Birth Day:</label>
      {{ members.birthDay }}
      {% csrf_token %}

      {{ members.Memebership_type.errors }}
      <label class="mybg4" for="{{ members.Memebership_type.id_for_label }}">Memebership type:</label>
      {{ members.Memebership_type }}
      {% csrf_token %}

      <p></p>

      {{ members.Email.errors }}
      <label class="mybg3" for="{{ members.Email.id_for_label }}">Email:</label>
      {{ members.Email }}
      {% csrf_token %}

      <p></p>

      {{ members.profile_image.errors }}
      <label class="mybg2" for="{{ members.profile_image.id_for_label }}">profile image:</label>
      {{ members.profile_image }}

      <!-- {% csrf_token %} -->


      <p></p>

      <input type="submit" class="btn btn-outline-danger btn-lg" name="" value="Submit">

    </form>
    {% endblock %}
  </body>
</html>

templates/members/index.html
{% extends "members/base.html" %}

<html>
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
  </head>
  <body>
    {% block body_block %}
    <div class="mybg1">
      <h1>Welcome To The Members Page</h1>
    </div>

    {% endblock %}

  </body>
</html>

templates/members/member_list.html
<!DOCTYPE html>
{% extends "members/base.html" %}
{% load staticfiles %}
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>List Data</title>
  </head>
  <body>
    {% block body_block %}
    <ol>
      {% for m in all_members %}
        <h3><li> <a href="{% url 'members:MembersDetails' slug=m.slug %}">{{ m.first_name }} {{m.last_name }} - Memebership Code: {{m.memebership_code}}</a> </li></h3>
      {% endfor %}
    </ol>
    {% endblock %}


  </body>
</html>